#!/usr/bin/python2.7
# -*- coding: utf-8 -*- # 这样在注释中打中文才不会报错

# Exercise 3: Numbers and Math------------------------------------------------------------------------------------------

# print "I will now count my chickens:"
# print "Hens", 25 + 30 / 6
# print "Roosters", 100 - 25 * 3 % 4
# print "Now I will count the eggs:"
#
# print 1 / 4  # 0 - It's not really rounding down; it's just dropping the fractional part after the decimal.
# print 1.0 / 4.0  # 0.25 - Try doing 7.0 / 4.0 and compare it to 7 / 4 and you'll see the difference.
#
# print 3 + 2 + 1 - 5 + 4 % 2 - 1 / 4 + 6
# print "Is it true that 3 + 2 < 5 - 7?"
# print 3 + 2 < 5 - 7
# print "What is 3 + 2?", 3 + 2
# print "What is 5 - 7?", 5 - 7
# print "Oh, that's why it's False."
# print "How about some more."
# print "Is it greater?", 5 > -2
# print "Is it greater or equal?", 5 >= -2
# print "Is it less or equal?", 5 <= -2

# ----------------------------------------------------------------------------------------------------------------------

# Exercise 4: Variables And Names---------------------------------------------------------------------------------------

# cars = 100
# space_in_a_car = 4.0
# drivers = 30
# passengers = 90
# cars_not_driven = cars - drivers
# cars_driven = drivers
# carpool_capacity = cars_driven * space_in_a_car
# average_passengers_per_car = passengers / cars_driven
#
#
# print "There are", cars, "cars available."
# print "There are only", drivers, "drivers available."
# print "There will be", cars_not_driven, "empty cars today."
# print "We can transport", carpool_capacity, "people today."
# print "We have", passengers, "to carpool today."
# print "We need to put about", average_passengers_per_car, "in each car."  # 只有分子分母都是float输出才是浮点型
#
# print "Hey %s there." % "you"

# ----------------------------------------------------------------------------------------------------------------------

# Exercise 5: More Variables and Printing-------------------------------------------------------------------------------
# my_name = 'Zed A. Shaw'
# my_age = 35  # not a lie
# my_height = 74  # inches
# my_weight = 180  # lbs
# my_eyes = 'Blue'  # 单双引号都是可以的
# my_teeth = 'White'
# my_hair = 'Brown'
#
# print "Let's talk about %s." % my_name
# print "He's %d inches tall." % my_height
# print "He's %d pounds heavy." % my_weight
# print "Actually that's not too heavy."
# print "He's got %s eyes and %s hair." % (my_eyes, my_hair)
# print "His teeth are usually %s depending on the coffee." % my_teeth
#
# # this line is tricky, try to get it exactly right
# print "If I add %d, %d, and %d I get %d." % (
#     my_age, my_height, my_weight, my_age + my_height + my_weight)
# print round(1.2333)  # 四舍五入
# ----------------------------------------------------------------------------------------------------------------------

# Exercise 6: Strings and Text------------------------------------------------------------------------------------------
# x = "There are %d types of people." % 10
# binary = "binary"
# do_not = "don't"
# y = "Those who know %s and those who %s." % (binary, do_not)
#
# print x
# print y
#
# print "I said: %r." % x
# # Use the %r for debugging, since it displays the "raw" data of the variable,
# # but the others are used for displaying to users.
#
# print "I also said: '%s'." % y
# # Mostly it's because of style, but I'll use a single-quote inside a string that has double-quotes.
# # Look at line 10 to see how I'm doing that.
#
# hilarious = False
# joke_evaluation = "Isn't that joke so funny?! %r"
#
# print joke_evaluation % hilarious
#
# w = "This is the left side of..."
# e = "a string with a right side."
#
# print w + e
# ----------------------------------------------------------------------------------------------------------------------

# Exercise 7: More Printing---------------------------------------------------------------------------------------------
# print "Mary had a little lamb."
# print "Its fleece was white as %s." % 'snow'
# print "And everywhere that Mary went."
# print "." * 10  # what'd that do?
#
# end1 = "C"
# end2 = "h"
# end3 = "e"
# end4 = "e"
# end5 = "s"
# end6 = "e"
# end7 = "B"
# end8 = "u"
# end9 = "r"
# end10 = "g"
# end11 = "e"
# end12 = "r"
#
# # watch that comma at the end.  try removing it to see what happens
# print end1 + end2 + end3 + end4 + end5 + end6,
# print end7 + end8 + end9 + end10 + end11 + end12
# ----------------------------------------------------------------------------------------------------------------------

# Exercise 8: Printing, Printing----------------------------------------------------------------------------------------
# formatter = "%r %r %r %r"
#
# print formatter % (1, 2, 3, 4)
# print formatter % ("one", "two", "three", "four")
# print formatter % (True, False, False, True)
# print formatter % (formatter, formatter, formatter, formatter)
# print formatter % (
#     "I had this thing.",
#     "That you could type up right.",
#     "But it didn't sing.",
#     "So I said goodnight."
# )
# print "%s" % "好"
# ----------------------------------------------------------------------------------------------------------------------

# Exercise 9: Printing, Printing, Printing------------------------------------------------------------------------------
# # Here's some new strange stuff, remember type it exactly.
#
# days = "Mon Tue Wed Thu Fri Sat Sun"
# months = "Jan\nFeb\nMar\nApr\nMay\nJun\nJul\nAug"
#
# print "Here are the days: ", days
# print "Here are the months: ", months
#
# print """
# There's something going on here.
# With the three double-quotes.
# We'll be able to type as much as we like.
# Even 4 lines if we want, or 5, or 6.
# """
# ----------------------------------------------------------------------------------------------------------------------

# Exercise 10: What Was That?-------------------------------------------------------------------------------------------
# tabby_cat = "\tI'm tabbed in."
# persian_cat = "I'm split\non a line."
# backslash_cat = "I'm \\ a \\ cat."
#
# fat_cat = """
# I'll do a list:
# \t* Cat food
# \t* Fishies
# \t* Catnip\n\t* Grass
# """
#
# print tabby_cat
# print persian_cat
# print backslash_cat
# print fat_cat
# ----------------------------------------------------------------------------------------------------------------------

# Exercise 11: Asking Questions-----------------------------------------------------------------------------------------
# print "How old are you?",
# age = raw_input()
# print "How tall are you?",
# height = raw_input()
# print "How much do you weigh?",
# weight = raw_input()
#
# print "So, you're %r old, %r tall and %r heavy." % (
#     age, height, weight)
# x = int(input())    # 3.3
# print x     # 3
# # What's the difference between input() and raw_input()?
# # The input() function will try to convert things you enter as if they were Python code,
# # but it has security problems so you should avoid it.
# ----------------------------------------------------------------------------------------------------------------------

# Exercise 12: Prompting People-----------------------------------------------------------------------------------------
# age = raw_input("How old are you? ")
# height = raw_input("How tall are you? ")
# weight = raw_input("How much do you weigh? ")
#
# print "So, you're %r old, %r tall and %r heavy." % (
#     age, height, weight)
# ----------------------------------------------------------------------------------------------------------------------

# Exercise 13: Parameters, Unpacking, Variables-------------------------------------------------------------------------
from sys import argv

script, first, second, third = argv

print "The script is called:", script
print "Your first variable is:", first
print "Your second variable is:", second
print "Your third variable is:", third
# ----------------------------------------------------------------------------------------------------------------------
